# Generated by Django 5.2.8 on 2025-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCrest', '0003_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(choices=[('B.Ed', 'B.Ed'), ('M.Ed', 'M.Ed'), ('M.Sc', 'M.Sc'), ('B.Sc', 'B.Sc'), ('PhD', 'PhD'), ('M.A', 'M.A'), ('B.A', 'B.A'), ('M.Com', 'M.Com'), ('B.Com', 'B.Com')], max_length=20),
        ),
    ]
