# Generated by Django 5.2.8 on 2025-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCrest', '0004_alter_teacher_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
