# Generated by Django 5.2.8 on 2025-12-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCrest', '0005_teacher_join_date_alter_teacher_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
