# Generated by Django 5.2.8 on 2025-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCrest', '0006_alter_teacher_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_divisions',
            field=models.ManyToManyField(blank=True, to='ClassCrest.classdivision'),
        ),
    ]
