# Generated by Django 5.2.8 on 2025-12-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCrest', '0007_classdivision_teacher_assigned_divisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all', 'All Users'), ('teachers', 'Teachers Only'), ('students', 'Students Only')], max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
