# Generated by Django 5.2.8 on 2025-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCrest', '0010_remove_teacher_subject_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=15)),
                ('period', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=100)),
            ],
        ),
    ]
